export const orderDetails = [
  {
    id: 0,
    buyer_name:'Seema Singh',
    profile_img:"logos/profile.svg",
    company: "Sunshine Apparel Pvt.Ltd",
    address:'Bangalore, Karnataka, India',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '500 mtrs',
    cost_bracket: 'INR 50 - INR 55 / mtr',
    lead_time_provision:'1 - 2 months',
    delivery_location :'New Delhi',
  },
  {
    id: 1,
    buyer_name:'Karan Sharma',
    profile_img:"logos/profile.svg",
    company: "Karan Enterprises",
    address:'New Delhi, India',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '500 mtrs',
    cost_bracket: 'INR 50 / mtr',
    lead_time_provision:'1 - 2 months',
    delivery_location :'New Delhi',
  },
  {
    id: 2,
    buyer_name:'Micheal Sheen',
    profile_img:"logos/profile.svg",
    company: "Label Sheen Pvt.Ltd.",
    address:'San Diego, California, USA',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '1000 mtrs',
    cost_bracket: 'USD 1 - USD 2 / mtr',
    lead_time_provision:'2 months',
    delivery_location :'San Diego, USA',
  },
  {
    id: 3,
    buyer_name:'Seema Singh',
    profile_img:"logos/profile.svg",
    company: "Sunshine Apparel Pvt.Ltd",
    address:'Bangalore, Karnataka, India',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '500 mtrs',
    cost_bracket: 'INR 50 - INR 55 / mtr',
    lead_time_provision:'1 - 2 months',
    delivery_location :'New Delhi',
  },
  {
    id: 4,
    buyer_name:'Karan Sharma',
    profile_img:"logos/profile.svg",
    company: "Karan Enterprises",
    address:'New Delhi, India',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '500 mtrs',
    cost_bracket: 'INR 50 / mtr',
    lead_time_provision:'1 - 2 months',
    delivery_location :'New Delhi',
  },
  {
    id: 5,
    buyer_name:'Micheal Sheen',
    profile_img:"logos/profile.svg",
    company: "Label Sheen Pvt.Ltd.",
    address:'San Diego, California, USA',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '1000 mtrs',
    cost_bracket: 'USD 1 - USD 2 / mtr',
    lead_time_provision:'2 months',
    delivery_location :'San Diego, USA',
  },
  {
    id: 6,
    buyer_name:'Seema Singh',
    profile_img:"logos/profile.svg",
    company: "Sunshine Apparel Pvt.Ltd",
    address:'Bangalore, Karnataka, India',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '500 mtrs',
    cost_bracket: 'INR 50 - INR 55 / mtr',
    lead_time_provision:'1 - 2 months',
    delivery_location :'New Delhi',
  },
  {
    id: 7,
    buyer_name:'Karan Sharma',
    profile_img:"logos/profile.svg",
    company: "Karan Enterprises",
    address:'New Delhi, India',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '500 mtrs',
    cost_bracket: 'INR 50 / mtr',
    lead_time_provision:'1 - 2 months',
    delivery_location :'New Delhi',
  },
  {
    id: 8,
    buyer_name:'Micheal Sheen',
    profile_img:"logos/profile.svg",
    company: "Label Sheen Pvt.Ltd.",
    address:'San Diego, California, USA',
    fabric: 'Organic Jersey',
    weight: '150 gsm',
    quantity: '1000 mtrs',
    cost_bracket: 'USD 1 - USD 2 / mtr',
    lead_time_provision:'2 months',
    delivery_location :'San Diego, USA',
  }
]
